"$schema" = "https://starship.rs/config-schema.json"

format = "$all"
right_format = "$time"

[dart]
disabled = true

[time]
disabled = false
time_format = "%H:%M"
format = "[$time]($style)"
style = "bold yellow"